# Configuration file for DiscordAwesomeStats

## Servers list
# If channels aren't specified, the message getting and stats generating will be done on every channel the bot has access to.
# Server id is required.
# Silent means no summary will be writed on the guild
# Report is the list of channels where the bot is supposed to write a summary message
#   Only the ID is needed, but it must match a channel which has been used by the bot.
# If the report_all has been set to True, it will write a summary message in every channels


guilds:
  # Sample guild
  - id: 564564654654546755
    channels:
      - 6546545656564564546
    report:
      - 6546545656564564546

  - id: 212131232132132312
    report_all: True
    silent: True

  - id: 213231123231213123
    silent: True


# Required for html output
outputdir: /tmp/DiscordAwesomeStats/

# Required for message getter
token: THISISNOTAREALTOKEN

# If not specified, use UTC.
timezone: 'Europe/Paris'